package com.gildedmc.core.modules;

/**
 * Hand-written training sentences. No frames, no slots, no placeholders.
 *
 * <h2>Why the generated corpus was replaced</h2>
 * The previous corpus was frames crossed with slots, and it scored 99.48%
 * held out. That number was not real. Train and test were drawn from the same
 * generator, so a held-out example was a near-duplicate of a training one —
 * same frame, different slot — and the model was being marked on paraphrases of
 * what it had already memorised. It also explains why every attempt to scale the
 * model failed: there was no additional signal for the extra capacity to learn.
 *
 * <p>These sentences are written individually. They vary in length, register,
 * punctuation, spelling and competence, the way a real chat log does. There are
 * far fewer of them than the generator produced, and they are worth more.
 * Expect the measured accuracy to <em>drop</em> — that is the point, because the
 * new number reflects performance on text the model has not effectively seen.
 *
 * <h2>What still gets generated</h2>
 * Only obfuscation, through {@link Mutations}. That is not a shortcut standing in
 * for variety: evasion genuinely is mechanical, players genuinely do type the
 * same sentence with dots swapped and letters spaced, and a transformation
 * applied by rule is exactly the right way to represent a transformation people
 * apply by rule.
 */
public final class HandWritten {

    private HandWritten() { }

    /* ================================================================== */
    /*  CLEAN — ordinary server chat                                      */
    /* ================================================================== */

    public static final String[] CLEAN = {
        "anyone selling diamonds",
        "wtb 2 stacks of iron paying 5k",
        "does anyone have spare bonemeal",
        "im at spawn if you want to trade",
        "how do i get to the nether hub from here",
        "my elytra broke can someone lend me one",
        "selling shulkers 3k each at my shop",
        "who wants to help me clear this jungle",
        "found a woodland mansion at like 4000 -2000",
        "the raid farm is finally done come see",
        "gg",
        "gg wp that was close",
        "lol",
        "lmao that was unlucky",
        "brb food",
        "back",
        "afk for a bit sorry",
        "anyone online",
        "hello",
        "hey how is everyone",
        "morning",
        "night all",
        "thanks",
        "ty so much",
        "np",
        "no worries mate",
        "sorry didnt mean to hit you",
        "my bad",
        "all good",
        "wait what happened",
        "how did you do that",
        "teach me that redstone thing sometime",
        "that build is actually insane",
        "took me like 6 hours to place all that",
        "im terrible at building honestly",
        "does anyone know where the end portal is",
        "server is lagging really bad right now",
        "tps dropped again",
        "is it just me or is chat broken",
        "restart when",
        "anyone got a spare bed i died",
        "lost everything in lava rip",
        "3 stacks of netherite gone lol",
        "who broke my chest",
        "someone stole all my stuff again",
        "raided again cool",
        "well that base lasted 2 days",
        "im rebuilding somewhere further out",
        "coords are 12000 -8000 if you wanna visit",
        "dont tell anyone my coords please",
        "trading emeralds for netherite scrap",
        "does the shop reset on sunday",
        "how much are shards going for now",
        "is the market crashed again",
        "prices are insane today",
        "can a mod check something for me",
        "reported a guy for hacking earlier",
        "screenshare that dude hes obvious",
        "he hits me through walls",
        "im pretty sure that was lag not hacks",
        "nah he was just good",
        "fair fight honestly",
        "rematch",
        "1v1 me at spawn",
        "you win that one",
        "how many cps do you click",
        "im on like 8 cps",
        "my mouse is dying",
        "new keyboard came today",
        "ping is 300 rn im cooked",
        "cant pvp on this wifi",
        "who is up for the end tonight",
        "we need 4 people minimum",
        "bring totems and gapples",
        "i have 12 totems spare",
        "anyone got obsidian",
        "need 64 obby for the portal",
        "crystal pvp is so expensive",
        "my whole inventory is anchors",
        "died to a crystal again",
        "i said the same thing",
        "come to minepvp",
        "minepvp",
        "fuckin",
        "fucking",
        "shit",
        "fuck",
        "keys",
        "key",
        "need keys",
        "looking for keys",
        // Relationship and identity statements. The old model read these as
        // hate because they name a player; they are the opposite of an attack.
        "angelogaming123 is my alt",
        "that guy is my alt account",
        "he is my brother irl",
        "she is my sister",
        "we are cousins playing together",
        "thats my friends main account",
        "im on my alt right now",
        "this is my main",
        "my alt is named something else",
        // Opinions. A view about a person or thing is not an attack.
        "i think he is cheating honestly",
        "in my opinion that was unfair",
        "imo the prices are too high",
        "i feel like the server got harder",
        "maybe it is just lag",
        "probably a bug",
        "might be his ping",
        "could be lag not hacks",
        "kinda annoying but whatever",
        "not gonna lie that was clean",
        "ngl i liked the old spawn better",
        // Skill talk aimed at players. Trash talk, never hate.
        "youre bad at pvp lol",
        "he is trash at crystal",
        "she is terrible at bedwars",
        "worst duo partner ever lmao",
        "get good kid",
        "skill issue tbh",
        "free win ez clap",
        "hard stuck gold haha",
        "no life much?",
        "carried the whole game",
        // Game vocabulary that once looked like hosts.
        "selling bamboo cheap",
        "bamboo for sale 10 per",
        "anyone want bamboo",
        "buying obsidian stacks",
        "netherite cheaper than here",
        "diamonds 5k each dm me",
        "selling diamond armor cheap dm me",
        "buying totems 500 each",
        "shop opening soon at spawn",
        "my shop has everything you need",
        "check out the player shops at spawn",
        "trading enchanted books for netherite",
        "wts elytra 30k message me",
        "wtb shulker shells bulk",
        "auction ending in 5 minutes",
        "highest bid wins my auction item",
        // Sarcastic/joking forms the classifier used to punish
        "yeah totally balanced gameplay",
        "very fair and normal pvp",
        "best server ever for sure",
        "great ping today love it",
        "love when the tps drops",
        "amazing plugin work as intended",
        // Player names ending in TLD-like suffixes must never flag
        "gg Angelogaming123",
        "Angelogaming123 just won the event",
        "wp NotchNet",
        "thanks DevMike",
        "is CoolDudeGG online?",
        "tell XrayTNT to hop on",
        "MrPvP_NET is hacking lol wait thats his name",
        // Elongation + caps mixes that once scored offences
        "GOOOOL that was funny",
        "looooooool brooo",
        "NAAAAH thats crazy",
        "yesssir we won",
        "LETS GOOOOO",
        "that was a clean combo",
        "how are you so fast",
        "practice i guess",
        "been playing since 2019",
        "im new here whats the deal with claims",
        "there are no claims here",
        "so anyone can break my stuff",
        "yeah thats the point of the server",
        "ok thats actually kinda fun",
        "welcome to anarchy",
        "hide your base and dont tell people",
        "best advice ive had all day",
        "whats the vote link",
        "do we get rewards for voting",
        "got a key from voting nice",
        "opened 10 keys and got nothing",
        "rng hates me",
        "finally got the rank",
        "congrats",
        "grats man",
        "how long did that take you",
        "like 40 hours of playtime",
        "i have 200 hours somehow",
        "touch grass lol",
        "says the guy with 400",
        "fair point",
        "whats everyone building",
        "just a storage system nothing special",
        "mine is a giant hole in the ground",
        "same honestly",
        "does anyone use shaders",
        "complementary is the best one",
        "my pc cant handle shaders",
        "i get 20 fps on low",
        "optifine or sodium",
        "sodium all day",
        "what version are we on",
        "1.21.4 i think",
        "does viaversion work here",
        "yeah you can join on older versions",
        "my friend wants to join is that ok",
        "sure just send them the ip",
        "whats our ip again",
        "its in the discord",
        "check the pinned message",
        "cant find the discord link",
        "its on the server list page",
        "anyone want to team",
        "we have 3 already",
        "room for one more",
        "im down",
        "lets go",
        "meet at spawn in 5",
        "on my way",
        "give me a sec",
        "ok im here",
        "where are you i dont see you",
        "look up",
        "found you",
        "follow me",
        "this way",
        "careful theres a drop",
        "too late lol",
        "you good",
        "lost half my stuff but yeah",
        "ill help you get it back",
        "youre a legend thanks",
        "anytime",
        "does anyone have food",
        "i have like 3 stacks of steak",
        "send some over",
        "dropped it by the fence",
        "got it cheers",
        "what mobs drop that again",
        "look it up on the wiki",
        "the wiki is wrong about that one",
        "trust me i tested it",
        "fair enough",
        "how does the enchant table work here",
        "same as vanilla",
        "level 30 or nothing",
        "got mending finally",
        "mending is so overpowered",
        "cant play without it now",
        "my pick has been alive for 3 months",
        "respect",
        "does anyone else lag near that farm",
        "yeah its the hoppers",
        "too many entities",
        "we should rebuild it",
        "ill help this weekend",
        "sounds good",
        "im off to bed",
        "night",
        "cya",
        "later",
        "have a good one",
        "see you tomorrow",
        "same time",
        "sounds like a plan"
    };

    /**
     * Blunt banter that is not punishable on a server with no claims.
     *
     * <p>This exists because removing the harassment class left the
     * "youre &lt;insult&gt;" shape present only in hate, and the model started
     * classifying trash talk as hate at full confidence. PvP is always on here
     * and this is the normal register after a fight; a filter that mutes it is
     * muting the game.
     */
    public static final String[] BANTER = {
        "youre trash at pvp",
        "youre actually dogwater",
        "that was so bad lol",
        "you play like you just installed the game",
        "my grandma clicks faster",
        "get better scrub",
        "ez",
        "ez clap",
        "get clapped",
        "you got absolutely destroyed",
        "washed",
        "youre washed bro",
        "hardstuck",
        "cope",
        "cope harder",
        "skill issue",
        "thats a skill issue honestly",
        "mid",
        "youre mid at best",
        "cooked",
        "he is so cooked",
        "im cooked",
        "we got cooked that round",
        "diff",
        "skill diff",
        "gear diff not skill",
        "you only won because of gear",
        "no shot you actually lost that",
        "how do you miss that",
        "my aim is horrendous today",
        "im playing so bad tonight",
        "worst game of my life",
        "that was embarrassing",
        "im never living that down",
        "clip that lol",
        "dont clip that please",
        "delete that clip",
        "youre never beating me",
        "keep dreaming",
        "in your dreams mate",
        "talk when you win one",
        "0 and 5 and still talking",
        "the trash talk is not matching the scoreboard",
        "all mouth no aim",
        "youre free",
        "free kill honestly",
        "easiest fight ever",
        "not even close",
        "sit down",
        "stay down",
        "get good",
        "gg ez no re",
        "close one though",
        "you nearly had me",
        "that was actually decent",
        "respect the effort",
        "nah you outplayed me there",
        "well played annoyingly",
        "rematch now",
        "run it back",
        "best of 5",
        "you got lucky",
        "luck is a skill",
        "sure it is",
        "your base is ugly",
        "my base is uglier dont worry",
        "who designed this thing",
        "it works dont judge",
        "function over form",
        "that redstone is cursed",
        "it does work though",
        "barely"
    };

    /**
     * Clean text sitting deliberately close to a boundary.
     *
     * <p>Every one of these was, at some point in this project, a measured false
     * positive. They are the examples that stop the model taking a shortcut —
     * that "kill" means a threat, a domain means advertising, "send me" means
     * nsfw, an email means a leak.
     */
    public static final String[] NEAR_MISS = {
        "im going to kill the ender dragon tonight",
        "killed him in pvp fair and square",
        "that creeper killed me again",
        "kill count is 40 to 12",
        "im on a killing spree",
        "this grind is killing me",
        "my fps is dying",
        "im dying laughing",
        "dead chat",
        "chat is dead lol",
        "i died at 500 30 -120",
        "the coords are -3000 12 8800",
        "my base is at 1200 70 -450",
        "meet me at 0 64 0",
        "my ping is 250 today",
        "we are on 1.21.4",
        "i have 64 diamonds and 128 iron",
        "my farm is at -820 71 340",
        "the wiki explains it better minecraft.fandom.com",
        "i read it on reddit.com earlier",
        "google.com is down for me",
        "the answer is on stackoverflow.com",
        "check the changelog on papermc.io",
        "download it from modrinth.com",
        "curseforge.com has the mod",
        "see the issue on github.com",
        "someone linked spigotmc.org",
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        "youtu.be/dQw4w9WgXcQ watch this",
        "check my youtube channel for the tutorial",
        "im streaming on twitch later",
        "my discord tag is in my profile",
        "add me on discord we can vc",
        "join our discord for updates",
        "bob@gmail.com is my email",
        "email me at someone@outlook.com",
        "my email is player123@yahoo.co.uk",
        "contact the owner at admin@example.org",
        "send me a screenshot of the base",
        "post pics of the build when done",
        "show me your farm design",
        "who wants to see my new storage",
        "dm me if you want to buy the shulker",
        "check my shop at spawn",
        "adult players only on this server",
        "this is an 18+ community",
        "mature players welcome",
        "i play on another server too",
        "the other server had a bad economy",
        "i used to play on a big network",
        "left that server months ago",
        "spam clicking is allowed right",
        "sorry for the spam my client froze",
        "stop spamming the trade chat",
        "my name in real life isnt my username",
        "i go to school with someone who plays here",
        "my phone died so i was afk",
        "221b baker street is fictional",
        "we went to 350 fifth avenue last summer",
        "bali is an island in indonesia",
        "the isle of skye is in scotland",
        "i hate this biome",
        "i hate lag not people",
        "shut up and take the win",
        "stop talking about the raid in main chat"
    };

    /* ================================================================== */
    /*  ADVERTISING                                                       */
    /* ================================================================== */

    public static final String[] ADVERTISING = {
        "join play.hypixel.net",
        "come play on 2b2t.org",
        "mc.hypixel.net is way better than here",
        "everyone hop on purpleprison.net",
        "free ranks at play.cubecraft.net",
        "server ip is manacube.com",
        "we have 500 players on pika-network.net",
        "leave this dead server and join complex-gaming.net",
        "play.wynncraft.com",
        "join us at herobrine.org",
        "hop on applecraft.org",
        "ip donutsmp.net",
        "connect to play.donutsmp.net",
        "everyone join loyalsmp.net",
        "come to skyblock.gg",
        "try opprison.net",
        "new server kitpvp.xyz check it out",
        "survivalmc.org is hiring staff",
        "better economy on hardcoresmp.net",
        "crystalpvp.gg has free ranks for the first 50",
        "im quitting for potpvp.xyz",
        "bedwars.gg no lag no queue",
        "dm me for the ip its skywars.net",
        "towny.xyz open beta now",
        "earthsmp.com giving away ranks",
        "we need players on lifesteal.gg",
        "this server sucks join boxsmp.net instead",
        "originsmp.xyz has crystal pvp",
        "vanillasmp.com 1.21 smp whitelist off",
        "our ip is modded.gg",
        "the address is createsmp.net",
        "we play on techsmp.xyz now",
        "everyone moved to mcprison.com",
        "play.skyblock.gg is the new server",
        "mc.lifesteal.gg has better staff",
        "come check join.boxsmp.net out",
        "45.62.11.7",
        "join 172.16.4.9:25565",
        "server ip 203.0.113.7:19132",
        "the ip is 51.79.62.14",
        "192.99.44.10:25565 come play",
        "play.example.net:25566 join now",
        "anyone want a better server dm me",
        "theres a way better smp than this one",
        "come to my server its way more active",
        "our server has 1000 players online right now",
        "we pay you to join our server",
        "looking for players for my new smp",
        "recruiting for a new lifesteal server",
        "my server has custom enchants and crates",
        "join the best crystal pvp server around",
        "if you want a real anarchy server message me",
        "this place is dead go somewhere else",
        "everyone from here moved servers already",
        "search up our name on planetminecraft",
        "look us up on minecraft server list",
        "we are top 10 on the server lists",
        "vote for us and get free ranks",
        "our discord has the ip pinned",
        "discord.gg/abcdefg for the ip",
        "join discord.gg/xyz123 to play with us",
        "check my bio for the server ip",
        "the ip is in my skin lol",
        "ill dm you the address",
        "ask me privately for the ip"
    };

    /* ================================================================== */
    /*  NSFW                                                              */
    /* ================================================================== */

    public static final String[] NSFW = {
        "send nudes",
        "send me nudes",
        "anyone got nudes",
        "post nudes in chat",
        "dm me nudes",
        "who wants to see nudes",
        "ill pay for nudes",
        "trade nudes with me",
        "im selling nudes",
        "got nudes to share",
        "send me your nudes",
        "anyone want to trade pics",
        "send me nsfw pics",
        "anyone got nsfw",
        "post nsfw here",
        "dm me nsfw content",
        "check my profile for nsfw",
        "my onlyfans is in my bio",
        "buy my onlyfans",
        "subscribe to my onlyfans",
        "im selling adult content",
        "adult links in my dms",
        "porn links here",
        "anyone got porn links",
        "im posting porn",
        "who wants porn",
        "free porn dm me",
        "explicit pics for sale",
        "send explicit photos",
        "18+ content in my dms",
        "18+ pics available",
        "hentai links anyone",
        "rule34 links in dms",
        "lewd pics for diamonds",
        "sending inappropriate photos",
        "who wants inappropriate pics",
        "revealing pics dm me",
        "im 12 send pics",
        "how old are you send pics",
        "asl and pics",
        "are you a girl send a pic",
        "girls dm me pics",
        "any girls here dm me",
        "im looking for a girlfriend send pics",
        "describe your body",
        "what are you wearing",
        "lets do it in dms",
        "join my private vc for adult stuff",
        "my server is 18+ only if you know what i mean",
        "sexual roleplay in dms anyone"
    };

    /**
     * Clean text that shares vocabulary with the nsfw class.
     *
     * <p>nsfw precision measured 78.6% - roughly one flag in five was wrong, and
     * the wrong ones were all of this shape: "send", "pics", "dm me", "hot",
     * "adult", "18+" are ordinary words that the class had monopolised. The fix
     * is not a higher threshold, it is showing the model the innocent uses.
     */
    public static final String[] NSFW_NEAR_MISS = {
        "send me the coords",
        "send me a screenshot",
        "send pics of the build",
        "send me the schematic",
        "send that over when you can",
        "send help im stuck in a hole",
        "can you send me some iron",
        "sending you the stuff now",
        "i sent it already check your chest",
        "post pics of your base",
        "post a screenshot in chat",
        "anyone got pics of the old spawn",
        "pics or it didnt happen",
        "nice pics of the build",
        "take a picture of the redstone",
        "my profile picture is a creeper",
        "changed my skin what do you think",
        "check my profile for my discord",
        "check my shop at spawn",
        "check out my new farm",
        "dm me the coords",
        "dm me if you want to trade",
        "dm me when youre online",
        "just dm me about it",
        "ill dm you the details",
        "message me if you need help",
        "hot bar is full",
        "my hotbar keeps swapping",
        "this lava is hot dont touch",
        "hot take but iron farms are boring",
        "adult players only on this server",
        "this is an 18+ community",
        "mature players welcome here",
        "im 18 if that matters",
        "how old is everyone here",
        "asking for a friend not weird",
        "that build is sexy ngl",
        "sexy redstone design",
        "your base is looking fine",
        "looking good so far",
        "show me what youve got",
        "show me your setup",
        "wanna see something cool",
        "come see my new build",
        "i want to see the farm",
        "who wants to see my storage",
        "trade me your elytra",
        "trading for netherite",
        "selling my whole base",
        "buying anything you have"
    };

    /**
     * Invitation frames, for crossing with the host list.
     *
     * <p>Used ONLY for advertising. The offence is literally "invite verb plus
     * an address", so the frame and the slot are the real structure of the thing
     * rather than a shortcut standing in for missing examples.
     */
    public static final String[] AD_FRAMES = {
        "join %s", "come play on %s", "%s is way better than here",
        "everyone hop on %s", "free ranks at %s", "server ip %s",
        "we have 500 players on %s", "leave this dead server and join %s",
        "%s", "play on %s", "join us at %s", "hop on %s", "ip %s",
        "connect to %s", "everyone join %s", "come to %s", "try %s",
        "new server %s check it out", "%s is hiring staff",
        "better economy on %s", "%s has free ranks", "im quitting for %s",
        "%s no lag no queue", "dm me for the ip its %s", "%s open beta now",
        "%s giving away ranks", "we need players on %s",
        "this server sucks join %s instead", "%s has crystal pvp",
        "%s 1.21 smp whitelist off", "our ip is %s", "the address is %s",
        "we play on %s now", "everyone moved to %s", "%s is the new server",
        "%s has better staff", "come check %s out", "%s needs builders",
        "%s is recruiting", "%s just opened", "%s is free to join",
        "get on %s before it fills", "%s beats this place",
        "tp for %s", "everyone go %s", "add %s", "%s join now",
        "playing on %s later", "who wants to join %s", "%s anyone",
        "come join %s now", "come join %s", "join %s its almost like here",
        "yall should hop on %s", "%s is so much better", "switching to %s",
        "we all play %s now", "quit this server come to %s",
        "%s free ranks join now", "free ranks on %s right now",
        "%s needs staff apply today", "staff apps open on %s",
        "%s has a better economy", "shop prices way lower on %s",
        "%s is way more fun", "everyone left this server for %s",
        "%s just reset join fresh", "fresh reset on %s come quick",
        "%s giveaway happening now", "rank giveaway on %s right now",
        "%s 1v1 me there", "crystal pvp on %s is insane",
        "%s has custom enchants", "custom enchants on %s check it",
        "we moved to %s permanently", "this place is dead %s is alive",
        "%s uptime is way better", "no queue on %s ever",
        "%s released yesterday already 100 players", "hundred players on %s day one",
        "stop playing here %s is where its at", "%s is the new meta",
        "add %s to your server list", "save %s to favorites",
        "%s season 3 launch today", "season reset tonight on %s",
        "first 100 joiners on %s get vip", "%s vote party in 10 mins",
        "bedrock and java both work on %s", "crossplay enabled on %s",
        "%s tps never drops", "zero lag on %s i promise",
        "my friend owns %s", "i am staff on %s",
        "%s application results tomorrow", "mod position open on %s",
        "you will get banned here but not on %s", "%s admins actually respond",
        "%s anticheat is optional", "cheats allowed on %s lol",
        "duping allowed on %s", "%s is anarchy no rules"
    };

    /** Real hosts, plus the host:port forms that were bypassing everything. */
    public static final String[] AD_HOSTS = {
        "play.hypixel.net", "mc.hypixel.net", "2b2t.org", "9b9t.com",
        "play.cubecraft.net", "hivemc.com", "play.mineplex.com",
        "play.wynncraft.com", "purpleprison.net", "mcmagic.us",
        "play.datblock.com", "archonhq.net", "manacube.com",
        "pika-network.net", "complex-gaming.net", "minecadia.com",
        "craftyourtown.com", "herobrine.org", "applecraft.org",
        "donutsmp.net", "play.donutsmp.net", "loyalsmp.net",
        "skyblock.gg", "opprison.net", "kitpvp.xyz", "survivalmc.org",
        "hardcoresmp.net", "crystalpvp.gg", "potpvp.xyz", "bedwars.gg",
        "skywars.net", "towny.xyz", "earthsmp.com", "lifesteal.gg",
        "boxsmp.net", "originsmp.xyz", "vanillasmp.com", "mcprison.com",
        "play.serverip.xyz", "serverip.xyz", "myserver.xyz", "bestsmp.xyz",
        "smpserver.com", "mcserver.xyz", "craftserver.net", "pvpserver.com",
        "anarchysmp.xyz", "lifestealsmp.net", "practice.gg", "joinme.xyz",
        "hateiscool.aternos.me", "myserver.minehut.gg", "smp.falix.gg",
        "berlin.caspianhost.com:30336", "bloodmoon.bot.nu:6001",
        "play.surgesmp.fun:20027", "unstablesmp.xubi.org",
        "51.79.62.14", "192.99.44.10:25565", "45.62.11.7",
        "172.16.4.9:25565", "play.example.net:25566", "mc.example.co.uk",
        // Dotless joined-token hosts — the shape "icemcpro" taught the model
        // that a bare run of letters can still be a destination when an invite
        // verb sits in front of it.
        "icemcpro", "coolpvpsmp", "topgurupvp", "megaskyblock",
        "ultralifesteal", "hyperprison", "omegafactions", "epic survival pvp",
        "thunderpvp", "wildprison", "frostskyblock", "vortexsmp",
        "10.0.0.1", "192.168.1.50:25565", "203.0.113.9",
        "novapvp", "titanmc", "zephyrsky", "ironfactions",
        "crimsonprison", "galaxysmp", "phantomlifesteal", "roguepvp",
        "198.51.100.7:25565", "203.0.113.99", "192.0.2.44"
    };

    /** More nsfw, hand-written. The class was 1,219 and too small to shape. */
    public static final String[] NSFW_MORE = {
        "drop your nudes",
        "who trading nudes",
        "nudes for 100k",
        "ill pay 500k for nudes",
        "selling nudes in dms",
        "got nudes dm me",
        "post your body",
        "show me your body",
        "send body pics",
        "any girls wanna trade pics",
        "girls only dm me pics",
        "send feet pics",
        "buying feet pics",
        "feet pics for diamonds",
        "who wants to sext",
        "lets sext in dms",
        "sexting anyone",
        "im horny dm me",
        "anyone horny here",
        "send something spicy",
        "spicy pics anyone",
        "got any spicy content",
        "check my of link",
        "my of is in bio",
        "subscribe to my of",
        "onlyfans link in dms",
        "selling my onlyfans",
        "join my nsfw discord",
        "nsfw server link dm me",
        "18+ discord anyone",
        "adult discord invite dm",
        "porn discord in dms",
        "sending porn links now",
        "who wants porn links",
        "free porn dm",
        "rule34 anyone",
        "hentai links dm me",
        "anime nsfw dm",
        "lewds anyone",
        "trading lewds",
        "send lewds pls",
        "post something explicit",
        "explicit content in dms",
        "im selling explicit pics",
        "how old r u send pic",
        "asl pics",
        "u a girl send pic",
        "prove ur a girl send pic",
        "send a pic of urself",
        "wanna see something naughty",
        "naughty pics dm",
        "dirty pics anyone",
        "send dirty pics",
        "erp anyone",
        "erp in dms",
        "roleplay 18+ dm me",
        "wanna erp",
        "im down to erp"
    };

    /**
     * nsfw frames and slots.
     *
     * <p>Same reasoning as advertising: "send me X" with X being the explicit
     * thing is the real shape of the offence. nsfw recall fell to 87.5% once
     * advertising reached 40,000 examples against its 2,625 - a class cannot
     * hold its own decision region at a fifteen-to-one disadvantage, and class
     * weighting only damps that, it does not erase it.
     */
    public static final String[] NSFW_FRAMES = {
        "send me %s", "send %s", "post %s in chat", "anyone got %s",
        "im looking for %s", "dm me %s", "who wants to see %s",
        "check my profile for %s", "trade me %s", "everyone should see %s",
        "ill pay for %s", "im selling %s", "add me if you want %s",
        "got %s to share", "send %s to my dms", "anyone trading %s",
        "here is %s enjoy", "i will send you %s", "who has %s",
        "message me for %s", "drop %s", "%s anyone", "buying %s",
        "selling %s in dms", "free %s dm me", "%s for diamonds",
        "%s for 100k", "trading %s only", "%s in my bio", "link to %s dm"
    };
    public static final String[] NSFW_ITEMS = {
        "nudes", "your nudes", "nsfw pics", "explicit pics", "18+ content",
        "adult links", "porn", "porn links", "lewd pics", "onlyfans links",
        "adult content", "explicit videos", "nsfw links", "18+ pics",
        "inappropriate photos", "revealing pics", "hentai", "rule34 links",
        "nsfw art", "explicit art", "lewd art", "adult pics", "body pics",
        "feet pics", "spicy pics", "dirty pics", "naughty pics",
        "something inappropriate", "explicit photos", "private pics"
    };

    /**
     * Targeted harassment frames — hate that carries no slur at all.
     *
     * <p>The owner asked for hate that is genuinely aimed at a person rather
     * than slur-shaped noise. These frames are cruelty aimed second-person:
     * Directed-hate frames — the owner was explicit: actual hate, actually
     * aimed. The %s slot is filled with a slur from {@link SeedCorpus}, so
     * every one of these carries a real slur aimed second-person or at a named
     * player. Slur-free "harassment" frames were tried and removed: they
     * blurred into ordinary trash talk and the owner rejected them.
     */
    public static final String[] HATE_FRAMES = {
        "you are a %s", "youre such a %s", "shut up %s",
        "all %s should be banned", "i hate every %s",
        "go back where you came from you %s", "%s like you ruin this server",
        "nobody wants %s here", "what a complete %s",
        "typical %s behaviour", "get out %s", "another %s joins great",
        "this server is full of %s", "kick the %s already",
        "%s arent welcome", "stop talking %s",
        "only a %s would build that", "im not playing with a %s",
        "every %s is the same", "youre just a %s and always will be",
        "delete your account %s", "leave the server %s",
        "i knew you were a %s", "%s should not be allowed online",
        "we dont want %s in this community",
        "go away %s", "youre nothing but a %s", "another %s great",
        "im done with %s players", "%s ruin every server",
        "why are there so many %s here", "report the %s already",
        "no wonder youre a %s", "keep crying %s", "%s go home",
        "stfu you %s", "shut your mouth you %s",
        "nobody likes a %s like you", "do everyone a favor %s and leave",
        "the world has enough %s already", "%s trash belongs in the bin",
        "you speak like a true %s", "act your age you %s",
        "%s detected opinion rejected", "blocked and reported you %s",
        "your kind %s isnt welcome on my team",
        "imagine being a %s in 2026", "touch grass you %s",
        "ratio plus youre a %s", "cope harder %s",
        "%s moment honestly", "classic %s behaviour as always",
        "everyone knows youre a %s now", "caught in 4k you %s",
        "%s spotted in the wild everyone", "absolute %s energy",
        "you type like a %s", "delete minecraft you %s",
        "%s shouldnt own a keyboard", "log off forever you %s"
    };

    /**
     * Ordinary-conversation frames for the clean class, crossed with
     * {@link #CLEAN_SLOTS}. The clean side needs volume too — a hate class at
     * 100k against a clean class at 30k teaches the model that unfamiliar
     * phrasing is probably an offence, which is exactly the failure mode the
     * owner kept hitting.
     */
    public static final String[] CLEAN_FRAMES = {
        "anyone selling %s", "buying %s pay well", "wtb %s dm me",
        "does anyone have spare %s", "trading %s for %s2", "selling %s cheap",
        "%s shop open at my base", "restocked my %s shop",
        "how much are %s worth now", "%s prices dropped again",
        "anyone know where to farm %s", "best way to get %s",
        "%s farm finally finished", "my %s farm broke again",
        "need help moving %s", "who took my %s",
        "found %s while mining", "got extra %s if anyone needs",
        "giving away free %s at spawn", "drop party %s for everyone",
        "anyone up for %s later", "%s event starting soon",
        "join our %s team", "looking for %s duo partner",
        "%s tournament this weekend", "won the %s contest",
        "lost all my %s in lava", "died with full %s inventory",
        "finally got %s after hours", "%s grind pays off",
        "is %s worth it endgame", "%s or save the shards",
        "new %s update when", "%s buff next patch pls",
        "%s is so expensive now", "inflation on %s is crazy",
        "someone scammed my %s", "scammer warning for %s trades",
        "%s giveaway at 500 players", "voting rewards %s keys",
        "crates gave me %s finally", "opened ten crates got %s",
        "%s from the vote crate nice", "free %s from voting daily",
        "where is the %s villager", "%s trader spawn location",
        "breeding %s tips", "afk %s pool design",
        "my %s storage system", "redstone %s sorter build",
        "%s dupe glitch patched?", "%s duping still works",
        "portal near %s coords", "%s at 1000 64 -2000",
        "base tour showing my %s", "%s hall almost done",
        "guarding my %s from raiders", "%s stash hidden good",
        "anyone seen my %s griefer took", "%s stolen report filed",
        "staff restored my %s", "rollback gave back my %s",
        "%s sale ends tonight", "black friday %s deals",
        "%s bundle offer dm", "bulk %s discount available",
        "%s restock incoming tomorrow", "supplier for %s here",
        "wholesale %s prices", "retail %s at my chest shop",
        "%s out of stock everywhere", "hoarding %s before update",
        "%s market crashed lol", "%s economy ruined by dupers",
        "investing in %s long term", "%s is the new currency",
        "paying %s for services", "hiring builders pay in %s",
        "%s loan request denied lol", "borrowed %s from town bank",
        "%s tax season on the smp", "mayor raised %s taxes again"
    };
    public static final String[] CLEAN_SLOTS = {
        "diamonds", "iron ingots", "gold blocks", "emeralds", "netherite scrap",
        "ancient debris", "shulker shells", "elytras", "totems", "enchanted books",
        "golden apples", "ender pearls", "blaze rods", "ghast tears", "quartz",
        "redstone dust", "lapis blocks", "cobblestone", "deepslate", "obsidian",
        "crying obsidian", "sand stacks", "gravel", "clay balls", "bamboo",
        "sugar cane", "wheat", "carrots", "potatoes", "beetroots",
        "pumpkins", "melons", "cactus", "kelp", "sea pickles",
        "prismarine shards", "nautilus shells", "sponges", "coral fans", "axolotls",
        "allays", "frogs", "axolotl buckets", "bees", "bee nests",
        "honey bottles", "slime balls", "magma cream", "phantom membranes", "dragon eggs",
        "nether stars", "beacons", "conduits", "tridents", "maces",
        "crossbows", "arrows", "spectral arrows", "respawn anchors", "lodestones",
        "spawners", "villagers", "zombie villagers", "iron golems", "snow golems",
        "horses", "donkeys", "llamas", "camels", "sniffers"
    };
}
